<?php
return [
    'data' => [
        [
            'id' => 1,
            'url_original' => 'https://www.google.com/search?q=laravel+eloquent',
            'slug' => 'a8b3k2',
            'click_count' => 152,
            'status' => 'active',
            'fk_user' => 1,
            'created_at' => '2025-02-23',
        ],
        [
            'id' => 2,
            'url_original' => 'https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt',
            'slug' => 'c7d9f1',
            'click_count' => 89,
            'status' => 'active',
            'fk_user' => 1,
            'created_at' => '2025-09-22',
        ],
        [
            'id' => 3,
            'url_original' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            'slug' => 'e2g8h5',
            'click_count' => 2048,
            'status' => 'inactive',
            'fk_user' => 1,
            'created_at' => '2025-02-21',
        ],
        [
            'id' => 4,
            'url_original' => 'https://tailwindcss.com/docs/installation',
            'slug' => 'f4j6k9',
            'click_count' => 340,
            'status' => 'active',
            'fk_user' => 1,
            'created_at' => '2025-09-20',
        ],
        [
            'id' => 5,
            'url_original' => 'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript',
            'slug' => 'h9m2n7',
            'click_count' => 512,
            'status' => 'expired',
            'fk_user' => 1,
            'created_at' => '2025-08-15',
        ],
        [
            'id' => 6,
            'url_original' => 'https://www.mercadolivre.com.br/ofertas',
            'slug' => 'k3p5r8',
            'click_count' => 78,
            'status' => 'active',
            'fk_user' => 1,
            'created_at' => '2025-09-19',
        ],
        [
            'id' => 7,
            'url_original' => 'https://g1.globo.com/ultimas-noticias/',
            'slug' => 'm6q9s2',
            'click_count' => 1205,
            'status' => 'active',
            'fk_user' => 1,
            'created_at' => '2025-09-18',
        ],
        [
            'id' => 8,
            'url_original' => 'https://br.linkedin.com/feed/',
            'slug' => 'n1t4v7',
            'click_count' => 45,
            'status' => 'active',
            'fk_user' => 2,
            'created_at' => '2025-09-17',
        ],
        [
            'id' => 9,
            'url_original' => 'https://stackoverflow.com/questions/tagged/php',
            'slug' => 'p8w3y6',
            'click_count' => 888,
            'status' => 'active',
            'fk_user' => 3,
            'created_at' => '2025-09-16',
        ],
        [
            'id' => 10,
            'url_original' => 'https://www.amazon.com.br/gp/goldbox',
            'slug' => 'r2z7x1',
            'click_count' => 0,
            'status' => 'inactive',
            'fk_user' => 4,
            'created_at' => '2025-09-15',
        ],
        [
            'id' => 11,
            'url_original' => 'https://laravel.com/docs/11.x/routing',
            'slug' => 's5a4b9',
            'click_count' => 401,
            'status' => 'active',
            'fk_user' => 2,
            'created_at' => '2025-09-14',
        ],
        [
            'id' => 12,
            'url_original' => 'https://www.figma.com/community/files',
            'slug' => 't9c8d2',
            'click_count' => 99,
            'status' => 'active',
            'fk_user' => 5,
            'created_at' => '2025-09-13',
        ],
        [
            'id' => 13,
            'url_original' => 'https://www.magazineluiza.com.br/',
            'slug' => 'v3e7f6',
            'click_count' => 23,
            'status' => 'expired',
            'fk_user' => 3,
            'created_at' => '2025-07-01',
        ],
        [
            'id' => 14,
            'url_original' => 'https://pt.wikipedia.org/wiki/P%C3%A1gina_principal',
            'slug' => 'x1g5h4',
            'click_count' => 180,
            'status' => 'active',
            'fk_user' => 6,
            'created_at' => '2025-09-11',
        ],
        [
            'id' => 15,
            'url_original' => 'https://openai.com/blog/chatgpt',
            'slug' => 'z9j2k1',
            'click_count' => 632,
            'status' => 'active',
            'fk_user' => 5,
            'created_at' => '2025-02-10',
        ],
    ]
];